[package]
name = "sha-1"
version = "0.8.1"
authors = ["Mingshen Sun <mssun@mesalock-linux.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
